### ISSUE TITLE
Session Not Ready To Browse

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#39] opened 2018-03-16 16:18 UTC
Sorry the last version 2.3.0 had not solved this problem.

NOW I can run a wireshark session sniffing the node-red instance mirroring a specific port that is working with a real OPC/UA server.

This is my test (injector -> browse node -> debug node) environment:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/15190791/37529999-d96f5d4a-2938-11e8-8a37-0d1b3fa59f64.png">

After connection (see state above) I get with wireshark:
![image](https://user-images.githubusercontent.com/15190791/37529892-968219d2-2938-11e8-8fc2-7f2ab547a142.png)

<img width="966" alt="image" src="https://user-images.githubusercontent.com/15190791/37530301-8112ddec-2939-11e8-9577-5031a74a69bf.png">

After triggering the injector (see above) i get with wireshark:
NOTHING!!!!!!

Apparently the session is not there. 

Can you assure it is working on a real OPC/UA server otherwise I must send this debug to the vendor

**Comment by biancode** [comment] 2018-03-16 18:11
hm interesting ... if Prosys Simulator is a real OPC UA server for you, then yes it works well with a real OPC UA server **IF** the certificate is set to trusted otherwise I got the same trouble as you described:

Certificate in server not trusted:
<img width="882" alt="screen shot 2018-03-16 at 19 05 49" src="https://user-images.githubusercontent.com/4369867/37537354-9532b9f0-294d-11e8-8fc0-53de441b330c.png">

Certificat in server trusted:
<img width="917" alt="screen shot 2018-03-16 at 19 06 37" src="https://user-images.githubusercontent.com/4369867/37537382-a35f603c-294d-11e8-9d51-13409ebfd507.png">


I'll try more with the Unified Automation servers too.

**Comment by biancode** [comment] 2018-03-16 18:36
Your problem is to reproduce with the Prosys server if ANONYMOUS is not allowed or user is wrong.
Is the Show Errors option checked in your flow in the Connector node settings?

Error: Cannot find ANONYMOUS user token policy in end point description

![image](https://user-images.githubusercontent.com/4369867/37538519-21e5234e-2951-11e8-8e28-f9f6196b30c6.png)

**Comment by biancode** [comment] 2018-03-16 18:36
![image](https://user-images.githubusercontent.com/4369867/37538579-564caec2-2951-11e8-986e-b950a6558b3b.png)

**Comment by biancode** [comment] 2018-03-16 18:37
![image](https://user-images.githubusercontent.com/4369867/37538630-82defb2a-2951-11e8-8ea3-e8a9917c84cc.png)

**Comment by biancode** [comment] 2018-03-16 18:38
![image](https://user-images.githubusercontent.com/4369867/37538653-8facf550-2951-11e8-8830-92f407f0b4ff.png)

**Comment by biancode** [comment] 2018-03-16 18:40
works with user too

![image](https://user-images.githubusercontent.com/4369867/37538763-ef223806-2951-11e8-8469-001868f73e11.png)

**Comment by biancode** [comment] 2018-03-16 21:52
ANONYMOUS works for me too if it is activated in server

![image](https://user-images.githubusercontent.com/4369867/37546319-98241cd4-296c-11e8-8520-109a88c04d35.png)

**Comment by biancode** [comment] 2018-03-16 21:53
<img width="670" alt="screen shot 2018-03-16 at 22 52 48" src="https://user-images.githubusercontent.com/4369867/37546377-c8b18b66-296c-11e8-9625-bb0a0e0cef7a.png">

**Comment by biancode** [comment] 2018-03-16 21:55
<img width="672" alt="screen shot 2018-03-16 at 22 54 41" src="https://user-images.githubusercontent.com/4369867/37546419-0cd78b38-296d-11e8-90e2-085c4be5dc05.png">

also in just ANONYMOUS mode

**Comment by biancode** [comment] 2018-03-16 22:03
please try v2.3.1

**Closed as completed** 2018-03-16 22:17 UTC
Labels: question, problem
