### ISSUE TITLE
Response and Listerner limited to 1000 variables

### ISSUE THREAD

**Issue by thecalle** [BiancoRoyal/node-red-contrib-iiot-opcua#87] opened 2019-02-26 16:30 UTC
I'm submitting an  unexpected behaviour.
   
**Current behaviour**: IIoT OPC UA Browse2Listener example scenario. Connect to OPC-UA server exposing 4000 variables, Response gives 1000 variables, Listener subscribes to 1000 variables.
 
**Expected behaviour**: Connect to server exposing 4000 variables, Response gives 4000 variables, Listener subscribes to 4000 variables.

**Environment:**
I am using just the Node-RED package and got node-opcua installed with it.

**Device** : Raspbian: GNU/Linux 9

**Comment by thecalle** [comment] 2019-03-01 10:18
Browsing also (using magnifing button) is limited to 1000!

**Comment by biancode** [comment] 2019-03-01 10:42
Hi, check your server settings! We use 10k nodes in other projects.

**Comment by thecalle** [comment] 2019-03-01 11:25
Hi Klaus. I connect to the same server using UaExpert Windows client and I get about 4K varibles under Tags. Node-red browser stops exactly at 999.

**Comment by biancode** [comment] 2019-03-01 12:17
v3.8.0 of the package? Please, Francesco, could you take a screenshot of the sever limits from UAExpert and push it here or send it by E-Mail!

**Comment by thecalle** [comment] 2019-03-01 13:15
Hi Klaus.

Package is v.3.8.0, here the screenshot feom UaExpert. I'm using our
Browser2Listen example to test.

Thanks in advance.

Francesco

[image: image.png]

Il giorno ven 1 mar 2019 alle ore 13:17 Klaus Landsdorf <
notifications@github.com> ha scritto:

**Comment by biancode** [comment] 2019-03-01 14:38
hm - no image to see here

**Comment by thecalle** [comment] 2019-03-01 15:12
Check now.

F.

Il giorno ven 1 mar 2019 alle ore 15:38 Klaus Landsdorf <
notifications@github.com> ha scritto:

**Comment by biancode** [comment] 2019-03-01 15:26
sorry, no image just 
[image: image.png]

**Comment by thecalle** [comment] 2019-03-04 07:17
Hi Klaus.

I think images are dropped by GITHub. Last mail has a correct .JPG attach

Francesco

Il giorno ven 1 mar 2019 alle ore 16:26 Klaus Landsdorf <
notifications@github.com> ha scritto:

**Comment by biancode** [comment] 2019-03-04 07:41
Please, just send it by E-Mail. I did not get any image. Just [image: image.png] also in the E-Mails

**Comment by biancode** [comment] 2019-03-04 16:33
![image](https://user-images.githubusercontent.com/4369867/53747467-9d3b2080-3ea3-11e9-9baa-72adfc164e77.png)

**Comment by thecalle** [comment] 2019-03-06 08:46
Hi Klaus.

I checked the parameter you suggested. The MaxNodesPerBrowse is set to
65536. All the parameters in Operation Limits are set to the same value.

Francesco.

Il giorno lun 4 mar 2019 alle ore 17:33 Klaus Landsdorf <
notifications@github.com> ha scritto:

**Comment by anthrogan** [comment] 2019-03-11 17:14
I have experienced similar with only returning 1000 tags, and ultimately bringing the opc server down (WinCC... Again! I can't confirm max nodes per browse either with wincc as the server does not expose this)

**Comment by biancode** [comment] 2019-03-15 19:14
How can I reproduce this use case?

**Comment by biancode** [comment] 2019-03-17 19:46
browse is restricted now from node-opcua and it will provide the browse next in a next step end of the month march 2019

**Comment by erossignon** [comment] 2019-04-07 16:43
@biancode  browse will limit the number of returned node to 1000 and will set a continuous point in the response if more than 1000 nodes exists. To get all the node , one shall call browseNext repeatedaly  until continous point becomes null.

**Comment by biancode** [comment] 2019-04-07 16:47
@erossignon you said it is not possible to call browseNext for now last time. Is it possible now and from which version of node-opcua, please?

**Comment by erossignon** [comment] 2019-04-07 18:11
on the client side, OPCUACLient#browseNext can be used since a long time and shall be available in v0.7.0.
version 2.0.0 will add further enhancements and browseNext support in the server and in the client crawler.

**Comment by biancode** [comment] 2019-12-14 21:19
![image](https://user-images.githubusercontent.com/4369867/70854703-bdcae900-1ebf-11ea-978e-085f493e0440.png)
browseNext works

**Comment by biancode** [comment] 2019-12-14 21:25
[6kNodesFlowBrowse.json.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/3964364/6kNodesFlowBrowse.json.zip)

needs v3.11.3 or above

**Comment by biancode** [comment] 2019-12-15 00:08
fixed with v3.12.0 - **but** the listener itself is also limited by the server how many items to be monitored at the same server

**Closed as completed by biancode** 2019-12-15 00:08 UTC
Labels: question, feature request, node-opcua issue, sponsors are welcome, pull request welcome
